var fs = require('fs');
eval(fs.readFileSync('clock.js')+'');

var assert = require('assert');
var voice = PatFleet;
assert.deepEqual(voice.getNumberPhrase(10),["10"]);
assert.deepEqual(voice.getNumberPhrase(1),["1"]);
assert.deepEqual(voice.getNumberPhrase(11),["11"]);
assert.deepEqual(voice.getNumberPhrase(20),["20"]);
assert.deepEqual(voice.getNumberPhrase(21),["20","1"]);

var date = new Date(2010,01,01,00,00,00,000);
assert.deepEqual(voice.getTimePhrase(date), ["at-tone-time-exactly","12","oclock","am"]);
date.setHours(12);
assert.deepEqual(voice.getTimePhrase(date), ["at-tone-time-exactly","12","oclock","pm"]);
date.setHours(13);
assert.deepEqual(voice.getTimePhrase(date), ["at-tone-time-exactly","1","oclock","pm"]);
date.setHours(22);
assert.deepEqual(voice.getTimePhrase(date), ["at-tone-time-exactly","10","oclock","pm"]);
date.setMinutes(1);
assert.deepEqual(voice.getTimePhrase(date), ["at-tone-time-exactly","10","oh","1","pm"]);
date.setMinutes(5);
assert.deepEqual(voice.getTimePhrase(date), ["at-tone-time-exactly","10","oh","5","pm"]);
date.setMinutes(10);
assert.deepEqual(voice.getTimePhrase(date), ["at-tone-time-exactly","10","10","pm"]);
date.setMinutes(11);
assert.deepEqual(voice.getTimePhrase(date), ["at-tone-time-exactly","10","11","pm"]);
date.setMinutes(20);
assert.deepEqual(voice.getTimePhrase(date), ["at-tone-time-exactly","10","20","pm"]);
date.setMinutes(21);
assert.deepEqual(voice.getTimePhrase(date), ["at-tone-time-exactly","10","20_","1","pm"]);
date.setMinutes(30);
assert.deepEqual(voice.getTimePhrase(date), ["at-tone-time-exactly","10","30","pm"]);
date.setSeconds(5);
assert.deepEqual(voice.getTimePhrase(date), ["at-tone-time-exactly","10","30","pm","and","5","seconds"]);
date.setSeconds(9);
assert.deepEqual(voice.getTimePhrase(date), ["at-tone-time-exactly","10","30","pm","and","9","seconds"]);
date.setSeconds(10);
assert.deepEqual(voice.getTimePhrase(date), ["at-tone-time-exactly","10","30","pm","and","10","seconds"]);
date.setSeconds(11);
assert.deepEqual(voice.getTimePhrase(date), ["at-tone-time-exactly","10","30","pm","and","11","seconds"]);
date.setSeconds(20);
assert.deepEqual(voice.getTimePhrase(date), ["at-tone-time-exactly","10","30","pm","and","20","seconds"]);
date.setSeconds(21);
assert.deepEqual(voice.getTimePhrase(date), ["at-tone-time-exactly","10","30","pm","and","20_","1","seconds"]);
date.setSeconds(25);
assert.deepEqual(voice.getTimePhrase(date), ["at-tone-time-exactly","10","30","pm","and","20_","5","seconds"]);
date.setSeconds(30);
assert.deepEqual(voice.getTimePhrase(date), ["at-tone-time-exactly","10","30","pm","and","30","seconds"]);
date.setSeconds(33);
assert.deepEqual(voice.getTimePhrase(date), ["at-tone-time-exactly","10","30","pm","and","30_","3","seconds"]);
date.setMinutes(0);
assert.deepEqual(voice.getTimePhrase(date), ["at-tone-time-exactly","10","oclock","pm","and","30_","3","seconds"]);
date.setHours(12);
assert.deepEqual(voice.getTimePhrase(date), ["at-tone-time-exactly","12","oclock","pm","and","30_","3","seconds"]);
date.setHours(0);
assert.deepEqual(voice.getTimePhrase(date), ["at-tone-time-exactly","12","oclock","am","and","30_","3","seconds"]);

console.log("All tests successful");
